version: '3'

services:
    db:
        image: mysql:5.7 # pulling image from DockerHub
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest # pulling image from DockerHub
        volumes:
            - ./wordpress:/var/www/html/wp-content
        ports:
            - 8001:80 # host:container
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

    website:
        depends_on:
            - wordpress
        image: php:apache # pulling image from DockerHub
        volumes:
            - ./website:/var/www/html # mount
        ports:
            - 8000:80  # host:container

volumes:
    db_data: